const CONSULTATION_TYPES = ["VIDEO", "AUDIO", "CHAT", "OFFLINE"];
const CONSULTATION_STATUSES = ["PENDING", "ACTIVE", "COMPLETED", "CANCELLED"];
const CONSULTATION_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

module.exports = {
    CONSULTATION_TYPES,
    CONSULTATION_STATUSES,
    CONSULTATION_RISK_LEVELS
};
